#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : helpdev
Version  : 0.7.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/16/8d/1909747368fef0cda0af1c570be578deff1f4fc3512c1e308c8fff73f359/helpdev-0.7.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/16/8d/1909747368fef0cda0af1c570be578deff1f4fc3512c1e308c8fff73f359/helpdev-0.7.1.tar.gz
Summary  : HelpDev - Extracts information about the Python environment easily.
Group    : Development/Tools
License  : MIT
Requires: helpdev-bin = %{version}-%{release}
Requires: helpdev-python = %{version}-%{release}
Requires: helpdev-python3 = %{version}-%{release}
Requires: importlib_metadata
Requires: psutil
BuildRequires : buildreq-distutils3
BuildRequires : psutil

%description
=======
        
        Helping users and developers to get information about the environment to
        report bugs or even test your system without spending a day on it. It can
        get information about hardware, OS, paths, Python distribution and packages,
        including Qt-things. Operates in Linux, Windows and Mac. Working on
        Python 2.7+ and Python 3.4+.
        
        If you want to get information at runtime of your application, you need
        to call using the same environment (and process) in which your application
        is running. This module can be imported and integrated into your application,
        providing a report about the current environment.
        
        Some information can be depedent or independent of your Python environment,
        and some others can be dependent your running application. So, there are some

%package bin
Summary: bin components for the helpdev package.
Group: Binaries

%description bin
bin components for the helpdev package.


%package python
Summary: python components for the helpdev package.
Group: Default
Requires: helpdev-python3 = %{version}-%{release}

%description python
python components for the helpdev package.


%package python3
Summary: python3 components for the helpdev package.
Group: Default
Requires: python3-core
Provides: pypi(helpdev)

%description python3
python3 components for the helpdev package.


%prep
%setup -q -n helpdev-0.7.1
cd %{_builddir}/helpdev-0.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596131730
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/helpdev

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
